version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_USER: collabuser
      POSTGRES_PASSWORD: collabpass
      POSTGRES_DB: collaboration
    ports:
      - "5432:5432"
    networks:
      - pg-network

  app:
    build: .
    container_name: collaboration-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/collaboration
      SPRING_DATASOURCE_USERNAME: collabuser
      SPRING_DATASOURCE_PASSWORD: collabpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - pg-network
    command: ["java", "-jar", "target/collaboration-app.jar"]

networks:
  pg-network:
